In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns

In [3]:
data=pd.read_csv("Admission_Predict.csv")
data.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [5]:
data.drop(["Serial No."],axis=1,inplace=True)
data.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [7]:
x=data.iloc[:,0:7].values
x

array([[337.  , 118.  ,   4.  , ...,   4.5 ,   9.65,   1.  ],
       [324.  , 107.  ,   4.  , ...,   4.5 ,   8.87,   1.  ],
       [316.  , 104.  ,   3.  , ...,   3.5 ,   8.  ,   1.  ],
       ...,
       [330.  , 116.  ,   4.  , ...,   4.5 ,   9.45,   1.  ],
       [312.  , 103.  ,   3.  , ...,   4.  ,   8.78,   0.  ],
       [333.  , 117.  ,   4.  , ...,   4.  ,   9.66,   1.  ]])

In [9]:
y=data.iloc[:,7:].values
y

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.

In [12]:
y.shape

(400, 1)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [14]:
y_train=(y_train>0.5)

In [15]:
y_train

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [16]:
y_test=(y_test>0.5)


In [17]:
y_test

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [

In [18]:
import importlib.util
from sklearn import datasets
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [19]:
cls = LogisticRegression(random_state=0)

In [20]:
lr=cls.fit(x_train,y_train)
y_pred = lr.predict(x_test)


a:\datasci\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
a:\datasci\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [21]:
y_pred

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [22]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix

In [23]:
print("\nAccuracy score: %f" %(accuracy_score(y_test,y_pred)*100))


Accuracy score: 91.250000


In [24]:
print("Recall score: %f" %(recall_score(y_test,y_pred)*100))

Recall score: 97.333333


In [25]:
print("ROC score : %f\n" %(roc_auc_score(y_test,y_pred)*100))

ROC score : 48.666667



In [26]:
print(confusion_matrix(y_test,y_pred))

[[ 0  5]
 [ 2 73]]


In [27]:
import pickle
pickle.dump(lr,open('university.pkl','wb'))
model=pickle.load(open('university.pkl','rb'))

In [30]:
import tensorflow as tf 
from tensorflow import keras
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.optimizers import Adam

In [31]:
model = keras.Sequential()
model.add(Dense(7,activation="relu",input_dim=7))
model.add(Dense(7,activation="relu"))
model.add(Dense(1,activation="linear"))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 7)                 56        
                                                                 
 dense_1 (Dense)             (None, 7)                 56        
                                                                 
 dense_2 (Dense)             (None, 1)                 8         
                                                                 
Total params: 120
Trainable params: 120
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.compile(loss="binary_crossentropy",optimizer='adam',metrics=['accuracy'])
model.fit(x_train,y_train,batch_size=20,epochs=100)

Epoch 1/100
16/16 [==============================] - 6s 24ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 2/100
16/16 [==============================] - 0s 10ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 3/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 4/100
16/16 [==============================] - 0s 5ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 5/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 6/100
16/16 [==============================] - 0s 6ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 7/100
16/16 [==============================] - 0s 5ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 8/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 9/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 10/100
16/16 [==============================] - 0s 5ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 1

Epoch 83/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 84/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 85/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 86/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 87/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 88/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 89/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 90/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 91/100
16/16 [==============================] - 0s 4ms/step - loss: 1.4296 - accuracy: 0.9062
Epoch 92/100
16/16 [==============================] - 0s 5ms/step - loss: 1.4296 - accuracy: 0.9062


In [35]:
model.save('model.h5')